apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.observability.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          derivedFields:
            - datasourceUid: tempo 
              matcherRegex: '"trace_id": "(\w+)"'
              name: TraceID
              url: $${__value.raw}
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        url: http://tempo.observability.svc.cluster.local:3100
        access: proxy
        isDefault: false
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: "tempo"
        url: http://tempo.observability.svc.cluster.local:3100
        access: proxy
        isDefault: false