apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels: { app: otel-collector }
data:
  otel.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4318"  # Onde o seu código Go envia os dados
          grpc:
            endpoint: "0.0.0.0:4317"

    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s

    exporters:
      otlphttp/tempo:
        endpoint: http://tempo.observability.svc.cluster.local:4318

      loki:
        endpoint: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/tempo]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
        

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"